name: Build and update docs on push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - uses: actions/setup-python@master
        with:
          python-version: '3.8'

      - name: Installing tools for environment
        run: python -m pip install --upgrade pip && python -m pip install pipenv

      - name: Initialising venv
        run: pipenv install --dev --system --verbose

      - name: Building docs
        run: make html
        working-directory: docs

      - name: Uploading docs as artifact
        uses: actions/upload-artifact@master
        with:
          name: docs
          path: docs/build/html

      - name: Cloning pages repo
        run: git clone  --depth 1 "https://github.com/${GITHUB_ACTOR}/${GITHUB_ACTOR}.github.io.git"

      - name: Updating docs
        run: |
          git rm -rf docs/${{ github.event.repository.name }} || echo "Docs for ${{ github.event.repository.name }} not found on ${GITHUB_ACTOR}.github.io.git, will be created"
          mkdir -p docs/${{ github.event.repository.name }}
          cp -avr ../docs/build/html/. docs/${{ github.event.repository.name }}/
        working-directory: ${{ github.actor }}.github.io

      - name: Set git config
        run: |
          git config --global user.email "${GITHUB_ACTOR}@https://users.noreply.github.com/"
          git config --global user.name "GitHub Actions Docs Update"

      - name: Checking diffs and uploading docs if necessary
        run: |
          git add --all
          git diff-index --quiet --cached HEAD -- && echo "No changes" && exit 0 || true
          git commit -m "${{ github.event.repository.name }}: ${GITHUB_SHA::8}"
          git push "https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_ACTOR}/${GITHUB_ACTOR}.github.io.git" master
        working-directory: ${{ github.actor }}.github.io
